
default: &default
  adapter: postgresql
  pool: 3306
  timeout: 5000
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: auth_app_development

test:
  <<: *default
  database: auth_app_test

production:
  <<: *default
  database: auth_app_production

